Repository tofubert/sechat-rs, pull requests merged in 2025-01, with the labels that each got.

#59 Refactor/backend requester
  Cargo.toml
  src/backend/mod.rs
  src/backend/nc_request/mod.rs
  src/backend/nc_request/nc_req_data_message.rs
  src/backend/nc_request/nc_req_data_room.rs
  src/backend/nc_request/nc_req_worker.rs
  src/backend/nc_request/nc_requester.rs
  src/backend/nc_room.rs
  src/backend/nc_talk.rs
  src/config/mod.rs
  src/main.rs
  src/ui/app.rs
  src/ui/chat_box.rs
  src/ui/chat_selector.rs
  src/ui/mod.rs
  src/ui/notifications.rs
  src/ui/title_bar.rs
  src/ui/users.rs
Labels: refactor

#50 Start writing docs for sechat-rs
  src/backend/mod.rs
  src/backend/nc_request/nc_request_ocs_wrapper.rs
  src/backend/nc_request/nc_requester.rs
  src/backend/nc_room.rs
  src/backend/nc_talk.rs
  src/main.rs
  src/ui/app.rs
  src/ui/mod.rs
  src/ui/widget/chat_box.rs
  src/ui/widget/chat_selector.rs
  src/ui/widget/help_box.rs
  src/ui/widget/input_box.rs
  src/ui/widget/mod.rs
  src/ui/widget/title_bar.rs
  src/ui/widget/users.rs
Labels: documentation

#63 add shutdown
  Cargo.toml
  src/backend/nc_request/nc_requester.rs
  src/backend/nc_talk.rs
  src/ui/app.rs
Labels: bug, enhancement

#68 update default dark theme
  Cargo.toml
  src/config/theme/options.rs
Labels: enhancement

#65 Feature/fetch full history
  src/backend/nc_message.rs
  src/backend/nc_request/nc_req_worker.rs
  src/backend/nc_request/nc_requester.rs
  src/backend/nc_room.rs
  src/backend/nc_talk.rs
  src/ui/app.rs
  src/ui/widget/chat_box.rs
  src/ui/widget/help_box.rs
Labels: enhancement
